# Generated by Django 5.2.5 on 2025-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_song_title_song_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
