# Generated by Django 5.2.5 on 2025-08-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_album_cover_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
