# Generated by Django 5.2.5 on 2025-08-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_song_unique_together_likedsong_song_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedsong',
            name='original_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
